### ISSUE TITLE
Working with attributes: 404 not found on data file

### ISSUE THREAD

**Issue by VeckoTheGecko** [spatialthoughts/qgis-tutorials#110]
The following link now has a 404 error. Alternative link still works.

https://github.com/spatialthoughts/qgis-tutorials/blob/13696e4849e4d16bd7afab3ca28a7c07dfbf2ac6/source/docs/working_with_attributes.rst?plain=1#L31

**Comment by VeckoTheGecko** [comment]
Even "fixing" the link to https://www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places_simple.zip doesn't work.

**Comment by spatialthoughts** [comment]
The updated link seems to be https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places_simple.zip

I have applied the fix on the newer version of thie tutorial #[bee1c58](https://github.com/spatialthoughts/qgis-tutorials/commit/bee1c58eb1fe36ceeb7fa2ae6b14e7c436875fbe)
https://www.qgistutorials.com/en/docs/3/working_with_attributes.html
