### ISSUE TITLE
Wrong expression in image 7.png

### ISSUE THREAD

**Issue by DiGro** [spatialthoughts/qgis-tutorials#12]
Ujaval,

whilst translating I noticed that the expression in image 7.png in Working with attributes (QGIS3)
is missing a "0".

Expression in the image is: "pop_max" > 100000 (five zero's) but should probably be "pop_max > 1000000 (six zero's)

Also effects some subsequent images with the selected points which should not be 3087 but 500

Greetings
Dick
![715](https://user-images.githubusercontent.com/5002095/58749105-c3139980-8481-11e9-939a-22bc86d1d022.png)

**Comment by spatialthoughts** [comment]
Thanks for the report. This was fixed but forgot to reply. 
https://www.qgistutorials.com/en/docs/3/working_with_attributes.html
