### ISSUE TITLE
Typo on handling_invalid_geometries.html

### ISSUE THREAD

**Issue by richarddunks** [spatialthoughts/qgis-tutorials#154]
The following contains a misspelled word:

> There is a graph-theory version of this **thorem** called [Five color theorem](https://en.wikipedia.org/wiki/Five_color_theorem)

Should be "theorem"

I'll try to submit a fix myself but wanted to make sure this was documented.

**Comment by spatialthoughts** [comment]
Thanks. If you want to send a fix, the source file is at https://github.com/spatialthoughts/qgis-tutorials/blob/master/source/docs/3/handling_invalid_geometries.rst. Just send a PR and I'll merge.

**Comment by spatialthoughts** [comment]
Fixed in 193714a4955018c29bb95536ea3c0260aa8afab2.
