### ISSUE TITLE
Big file in .git

### ISSUE THREAD

**Issue by felipeacsi** [spatialthoughts/qgis-tutorials#2]
Hello,

When I ran `git clone` for this repo takes a lot time to download all files. This is partly because there are files that help in the tutorials but there is a particular file of ~500 MB in `qgis-tutorials/.git/objects/pack/`. Did you know the existence of this file? I do not know much git but searching it seems this file contains info about other large files.

It would be good if you can "remove" this file **only if** is not very relevant. Unfortunately I tried some solutions found in Stackoverflow but they did not work.

**Comment by spatialthoughts** [comment]
Use the following clone command to get only the latest files. This should be quite small
git clone --depth 1 git@github.com:spatialthoughts/qgis-tutorials.git
